#!/bin/bash
docker-compose run -d rabbitmq
docker-compose run -d postgres
docker-compose run -d --service-ports -e DOCKER_MACHINE_IP=$(docker-machine ip) database-interface
docker-compose run -d --service-ports -e DOCKER_MACHINE_IP=$(docker-machine ip) tms-interface
docker-compose run -d --service-ports -e DOCKER_MACHINE_IP=$(docker-machine ip) tcs
