SELECT
	to_char(CALL_TIME,'Day') AS "Day", to_char(CALL_TIME, 'D') AS "Day#",
	COUNT(*) AS "No. of users"
FROM
	RAW_CALL,
	TRUNK
WHERE
	RAW_CALL.PARTY_2_DEVICE = TRUNK. ID
AND TRUNK. ID <> 'CBUS'
AND CALL_TIME > DATE '2015-01-01' - INTERVAL '12 months'
AND DIRECTION = 'I'
GROUP BY
	1,2
ORDER BY
	2
	