#!/bin/bash

echo 'QA Test Run Begins'
export PATH=$PATH:./scripts

# Prepare the QA environment
cp jenkins/.tcs.env .
cp jenkins/.tcs.version .
. $WORKSPACE/.project.bash

# Select the test environment
tcsenv QA

# Ensure that any existing QA containers are down
tcs down

# Then start the new ones
tcs

# Testing begins
docker-compose $COMPOSE_ARGS run --rm --name QA-integrate --entrypoint bash integrate $WORKSPACE'./lib/integrate/test-pbx-to-tms-flow.js'