#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' backup_id [target_time]'

if [ $# == 1 ]; then
	if [ $1 == 0 ]; then 
		DETAIL_LEVEL=&>/dev/null
	elif [ $1 == 1 ]; then
		DETAIL_LEVEL=2>&1 >/dev/null
	elif [ $1 == 2 ]; then
		DETAIL_LEVEL=''
	else
		error-exit "$USAGE";
	fi
fi

exit 0

echo 'Building Images ... '
source .tcs.version
docker-compose $STORES_COMPOSE_ARGS build 2>&1 >/dev/null || exit 1;
docker login -u ccbcadmin -p 2620Turner || exit 1;
docker push 'ccbcadmin/tcs-image'$TCS_VERSION || exit 1;
docker push 'ccbcadmin/tcs-jenkins'$TCS_VERSION || exit 1;

echo $PROGNAME' Complete'
exit 0
