#!/bin/bash

PROGNAME=$(basename $0)

echo 'Building Images ... '
source .tcs.version
docker-compose $STORES_COMPOSE_ARGS build 2>&1 >/dev/null || exit 1;
docker login -u ccbcadmin -p 2620Turner || exit 1;
docker push 'ccbcadmin/tcs-image'$TCS_VERSION || exit 1;
docker push 'ccbcadmin/tcs-jenkins'$TCS_VERSION || exit 1;

echo $PROGNAME' Complete'
exit 0
