#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' backup_id target_time'

source ./scripts/bash-functions

if [ "$#" != 1 ] && [ "$#" != 2 ] ; then error-exit "$USAGE"; fi

validate-backup_id $1 || exit 1;

# Remove the offline container, before doing the recovery
remove-stores-container pg2

# Do the recovery
case "$#" in
	1)	barman-recover pg2 $1 || error-exit 'Recovery Failure';;
	2)  barman-pitr pg2 $1 $2 || error-exit 'Recovery Failure';;
	*)  error-exit 'Assertion Error @ '$LINENO ;;
esac
msg 'Recovery Successful'

# Ensure Postgres owns everything
change-pgdata-owner postgres pg2 || exit 1;

# Finally bring up the offline container to listen on port 5433
start-stores-container pg2 || exit 1;

msg 'Offline Recovery Complete'
exit 0
