#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' backup_id target_time'

source ./scripts/bash-functions

if [ "$#" != 1 ] && [ "$#" != 2 ] ; then error-exit "$USAGE"; fi

validate-backup_id $1

# Remove the offline container, before doing the recovery
remove-stores-container pg2

# Do the recovery
case "$#" in
	1)	if ! barman-recover pg2 $1; then error-exit 'Recovery Failure'; fi ;;
	2)  if ! barman-pitr pg2 $1 $2; then error-exit 'Recovery Failure'; fi ;;
	*)  error-exit 'Assertion Error @ '$LINENO ;;
esac
msg 'Recovery Successful'

# Ensure Postgres owns everything
if ! change-pgdata-owner postgres pg2; then exit 1; fi

# Finally bring up the offline container to listen on port 5433
if ! start-stores-container pg2; then exit 1; fi

msg 'Offline Recovery Complete'
exit 0
