#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' pg1|pg2 backup_id [target_time]'

source ./scripts/bash-functions

if [ "$#" != 3 ]; then error-exit "$USAGE"; fi

validate-pg-selection $1 "$USAGE"

validate-backup_id $1 $2

# Ensure that inflows to the database are stopped
stop-container database-interface

# Get the statuses of the Postgres containers
pg-statuses

# Shutdown the outgoing container
remove-container $ACTIVE_PG

# Do the recovery
barman-pitr $ACTIVE_PG $1 $2 $3

# Restart the container
start-pg-container $ACTIVE_PG 5432; sleep 2; 

enable-stream-replication $ACTIVE_PG

# Restart the inflow to the database
start-container database-interface

msg 'Postgres Container Rollback Complete'
exit 0
