#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' pg1|pg2 backup_id [target_time]'

source ./scripts/bash-functions
source ./.tcs-pg-ports

echo -n "Executing this command will result in data loss.  Proceed? [yes or no]: "
read yno
case $yno in
    [yY] | [yY][Ee][Ss] )
        ;;
    [nN] | [n|N][O|o] )
        echo "Command aborted.";
        exit 1
        ;;
    *) echo "Invalid input"
		exit 1
        ;;
esac

if [ "$#" != 2 ] && [ "$#" != 3 ] ; then error-exit "$USAGE"; fi

validate-pg-selection $1 "$USAGE"

validate-backup_id $1 $2

# Get the statuses of the Postgres containers
pg-state &> /dev/null

# Shutdown the active Postgres container
remove-core-container $ACTIVE_PG

# Do the recovery
case "$#" in
	2)	if ! barman-recover $ACTIVE_PG $@; then error-exit 'Recovery Failure'; fi ;;
	3)  if ! barman-pitr $ACTIVE_PG $@; then error-exit 'Recover Failure'; fi ;;
	*)  error-exit 'Assertion Error @ '$LINENO ;;
esac

# Now restart the Postgres container
if ! start-active-pg-container $ACTIVE_PG; then exit 1; fi

msg 'Rollback Recovery Complete'
exit 0
