#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' backup_id [target_time]'

source ./scripts/bash-functions

echo -n "Executing this command will result in data loss.  Proceed? [yes or no]: "
read yno
case $yno in
    [yY] | [yY][Ee][Ss] )
        ;;
    [nN] | [n|N][O|o] )
        echo "Command aborted.";
        exit 1
        ;;
    *) echo "Invalid input"
		exit 1
        ;;
esac

if [ "$#" != 1 ] && [ "$#" != 2 ]; then error-exit "$USAGE"; fi

if ! validate-backup_id $1; then return 1; fi

# Shutdown the operational Postgres container
if ! remove-stores-container pg1; then exit 1; fi

# Do the recovery
case "$#" in
	1)	if ! barman-recover pg1 $1; then error-exit 'Recovery Failure'; fi ;;
	2)  if ! barman-pitr pg1 $1 $2; then error-exit 'Recovery Failure'; fi ;;
	*)  error-exit 'Assertion Error @ '$LINENO ;;
esac

echo 'Here 1'
# Now restart the Postgres container
if ! start-active-pg-container; then exit 1; fi

echo 'Here 2'

msg 'Rollback Recovery Complete'
exit 0
