#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' pg1|pg2 backup_id target_time'

source ./scripts/bash-functions

if [ "$#" != 3 ]; then error-exit "$USAGE"; fi

validate-pg-selection $1 "$USAGE"

validate-backup_id $1 $2

# Ensure that inflow to the database is stopped
container-exists database-interface
if [ "$?" == 0 ]; then stop-container database-interface; fi

# Remove both pg containers
remove-container pg1
remove-container pg2

# Do the recovery
barman-pitr $1 $2 $3

# Start the pg container
start-pg-container $1 5432; sleep 2

enable-stream-replication $1

# Restore inflow to the database
container-exists database-interface
if [ "$?" == 0 ]; then start-container database-interface; fi

msg 'Postgres Recovery Complete'
exit 0
