#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' backup_id target_time'

source ./scripts/bash-functions

if [ "$#" != 1 ] && [ "$#" != 2 ] ; then error-exit "$USAGE"; fi

validate-backup_id $1

# Get the pg statuses (Active or PITR)
pg-state &> /dev/null

# Remove the STANDBY container, before doing the recovery
remove-stores-container pg2

# Do the recovery
case "$#" in
	2)	if ! barman-recover pg2 $@; then error-exit 'Recovery Failure'; fi ;;
	3)  if ! barman-pitr pg2 $@; then error-exit 'Recovery Failure'; fi ;;
	*)  error-exit 'Assertion Error @ '$LINENO ;;
esac
msg 'Recovery Successful'

# Ensure Postgres owns everything
if ! change-pgdata-owner postgres pg2; then exit 1; fi

# Finally bring up the STANDBY container to listen on port 5433
if ! start-stores-container pg2; then exit 1; fi

msg 'Standby Recovery to pg2 Complete'
pg-state
exit 0
