#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' pg1|pg2 backup_id target_time'

source ./scripts/bash-functions

if [ "$#" != 3 ]; then error-exit "$USAGE"; fi

validate-pg-selection $1 "$USAGE"

validate-backup_id $1 $2

# Get the pg statuses (Active or PITR)
pg-statuses

# Ensure what is to be the PITR container is removed (for the moment)
remove-container $PITR_PG
msg $PITR_PG' Container Removed'

# Do the recovery
barman-pitr $PITR_PG $1 $2 $3

# Finally bring up the PITR container to listen on port 5433
start-pg-container $PITR_PG 5433; sleep 2;
enable-stream-replication $PITR_PG 5433

msg 'Point-In-Time Recovery to Container '$PITR_PG' Complete'
exit 0
