#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' pg1|pg2 backup_id target_time'

source ./scripts/bash-functions
source ./.tcs-pg-ports

if [ "$#" != 2 ] && [ "$#" != 3 ] ; then error-exit "$USAGE"; fi

validate-pg-selection $1 "$USAGE"

validate-backup_id $1 $2

# Get the pg statuses (Active or PITR)
pg-status &> /dev/null

# Remove the STANDBY container, before doing the recovery
remove-core-container $STANDBY_PG

# Do the recovery
case "$#" in
	2)	if ! barman-recover $STANDBY_PG $@; then error-exit 'Recovery Failure'; fi ;;
	3)  if ! barman-pitr $STANDBY_PG $@; then error-exit 'Recovery Failure'; fi ;;
	*)  error-exit 'Assertion Error @ '$LINENO ;;
esac
msg 'Recovery Successful'

# Finally bring up the STANDBY container to listen on port 5433
if ! start-pg-container $STANDBY_PG; then exit 1; fi

msg 'Standby Recovery to '$STANDBY_PG' Complete'
pg-status
exit 0
