#!/bin/bash

PROGNAME=$(basename $0)

# Allow access to bash scripts
export PATH=./scripts:$PATH

# define various functions
source scripts/bash-functions

# Default to production
tcsenv prod

if [ $# -gt 1 ]; then echo "Usage : tcsproj [ TCS Version ]"; exit 1; fi

# If a version number is provided, then ensure that it is of the required form
VERSION_REGEX="^v[0-9]+\.[0-9]+$"
if [ $# -eq 1 ]; then
    if ! [[ $1 =~ $VERSION_REGEX ]]; then
        echo 'TCS Version must be of the form vX.Y, where X and Y are both integers'
        exit 1
    else
        # Ensure TCS software is up-to-date
        if ! git pull 2>&1 >/dev/null; then msg 'Pull from GitHub Failed'; return 1; fi
        if ! git checkout tags/$1 -b $1 2>&1 >/dev/null; then 
            msg 'Branch '$1' Already Exists Failed'; 
            git checkout $1;
        fi
        echo 'export TCS_VERSION=:'$1 > ./.tcs.version
    fi
fi

# Load TCS environment variables
. ./.tcs.version
if ! [ -f .tcs-pg-ports ]; then set-pg-ports pg1; fi
source ./.tcs-pg-ports;

echo 'TCS Version'$TCS_VERSION

# Load some project-specific aliases
source ./scripts/aliases