#!/bin/bash

PROGNAME=$(basename $0)

# Allow access to bash scripts
export PATH=./scripts:$PATH

# define various functions
source scripts/bash-functions

# Default to production
tcsenv prod &>/dev/null

if [ $# -gt 1 ]; then echo "Usage : tcsproj [ TCS Version ]"; exit 1; fi

# If a version number is provided, then ensure that it is of the required form
VERSION_REGEX="^v[0-9]+\.[0-9]+$"
if [ $# -eq 1 ]; then
    if ! [[ $1 =~ $VERSION_REGEX ]]; then
        echo 'TCS Version must be of the form vX.Y, where X and Y are both integers'
        exit 1
    else
        # Go back to the master before proceeding
        if ! git checkout master 2>&1 >/dev/null; then
            msg 'git checkout master failed';
            return 1;
        fi
        # Ensure TCS software is up-to-date
        if ! git pull 2>&1 >/dev/null; then 
            msg 'git pull failed'; 
            return 1; 
        fi
        if ! git checkout tags/$1 -B $1 2>&1 >/dev/null; then 
            msg 'git checkout failed'; 
            return 1;
        fi
    fi
fi

# export the version
source ./.tcs.version

echo 'TCS Version'$TCS_VERSION

# Load some project-specific aliases
source ./scripts/aliases
