#!/bin/bash

PROGNAME=$(basename $0)

source ./scripts/bash-functions

if is-pg1-active; then
	docker exec -it pg1 psql --username postgres -p 5432 -d $TCSENV
elif container-exists pg1; then
	echo 'pg1 STOPPED'
else
	echo 'pg1 GONE'
fi
exit 0;