#!/bin/bash

PROGNAME=$(basename $0)

source ./scripts/bash-functions

if is-pg1-active == 0; then
	echo 'pg1 ACTIVE'
	docker exec -it pg1 psql --username postgres -p 5432
elif is-pg1-pitr == 0; then
	echo 'pg1 STANDBY'
	docker exec -it pg1 psql --username postgres -p 5433
elif container-exists pg1; then
	echo 'pg1 STOPPED'
else
	echo 'pg1 GONE'
fi
