#!/bin/bash

PROGNAME=$(basename $0)

source ./scripts/bash-functions

if is-pg2-standby == 0; then
	docker exec -it pg2 psql --username postgres -p 5433 -d $TCSENV
elif container-exists pg2; then
	echo 'pg2 STOPPED'
else
	echo 'pg2 GONE'
fi
