#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME

source ./scripts/bash-functions

if [ "$#" != 0 ]; then error-exit "$USAGE"; fi

docker-compose $STORES_COMPOSE_ARGS down || exit 1;
exit 0;
