#!/bin/bash

PROGNAME=$(basename $0)
source ./scripts/bash-functions

COMPOSE_ARGS=" -f docker-compose/docker-compose.yml -f docker-compose/dev/docker-compose.yml -p dev "

docker-compose $COMPOSE_ARGS up -d --no-build pbx-interface
if [ $? != 0 ]; then error-exit 'Failed to Start TCS Containers'; fi

msg 'TCS (DEV) Started'
