#!/bin/bash

PROGNAME=$(basename $0)
source ./scripts/bash-functions

COMPOSE_ARGS=" -f docker-compose.yml -f docker-compose-qa.yml -p qa "

# Ensure we have the correct image and, if not, go get it
if [ -z ${TCS_VERSION+x} ]; then echo "TCS_VERSION undefined"; exit 1; fi
if ! docker pull ccbcadmin/tcs-image$TCS_VERSION; then exit 1; fi

docker-compose $COMPOSE_ARGS up -d --no-build pbx-interface
if [ $? != 0 ]; then error-exit 'Failed to Start TCS Containers'; fi

msg 'TCS (QA) Started'
