#!/bin/bash

PROGNAME=$(basename $0)
source ./scripts/bash-functions

docker-compose $DEV_COMPOSE_ARGS up -d --no-build pbx-interface
if [ $? != 0 ]; then error-exit 'Failed to Start TCS Containers'; fi

msg 'TCS (DEV) Started'
