#!/bin/bash

PROGNAME=$(basename $0)
USAGE='Usage: '$PROGNAME' dev|qa|prod'

source ./scripts/bash-functions

# ensure input params validity
if [ "$#" != 1 ]; then error-exit "$USAGE"; fi

case "$1" in
	[dD][eE][vV])
		echo Mode is dev
		export COMPOSE_ARGS=$DEV_COMPOSE_ARGS
		echo $COMPOSE_ARGS
		exit 0
		;;
	[qQ][aA])
		echo Mode is qa
		exit 0
		;;
	[pP][rR][oO][dD])
		echo Mode is prod
		exit 0
		;;
	*) error-exit "$USAGE";
		;;
esac

